import os


def export_cookies_to_netscape(
    cookie_string: str,
    output_path: str,
):
    """
    将 Cookie 字符串导出为 Netscape 格式的 cookie 文件。
    cookie_string 格式: "name1=value1; name2=value2"
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by bilibili-monitor. Edit at your own risk.",
        "",
    ]
    domain = ".bilibili.com"
    future = "4102444800"

    for item in cookie_string.split(";"):
        item = item.strip()
        if not item:
            continue
        if "=" not in item:
            continue
        name, value = item.split("=", 1)
        if name and value:
            lines.append(f"{domain}\tTRUE\t/\tFALSE\t{future}\t{name}\t{value}")

    folder = os.path.dirname(output_path)
    if folder:
        os.makedirs(folder, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
