import os


def export_cookies_to_netscape(
    sessdata: str, bili_jct: str, buvid3: str, dedeuserid: str, output_path: str
):
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by bilibili-monitor. Edit at your own risk.",
        "",
    ]
    domain = ".bilibili.com"
    future = "4102444800"

    cookies = {
        "SESSDATA": sessdata,
        "bili_jct": bili_jct,
    }
    if buvid3:
        cookies["buvid3"] = buvid3
    if dedeuserid:
        cookies["DedeUserID"] = dedeuserid

    for name, value in cookies.items():
        if value:
            lines.append(f"{domain}\tTRUE\t/\tFALSE\t{future}\t{name}\t{value}")

    folder = os.path.dirname(output_path)
    if folder:
        os.makedirs(folder, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
